{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-postgresql
  labels:
    app: {{ .Chart.Name }}-postgresql
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: postgresql
  selector:
    app: {{ .Chart.Name }}-postgresql
{{- end }}