name: Deploy Application

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'helm/**'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Kubeconfig
      uses: actions/download-artifact@v3
      with:
        name: kubeconfig
        path: $HOME/.kube/

    - name: Configure GCP Credentials
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ env.GKE_SA_KEY }}
        export_default_credentials: true

    - name: Get GKE Credentials
      run: |
        gcloud container clusters get-credentials my-new-env --region us-central1

    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: "3.12.0"

    - name: Install/Upgrade Helm Chart
      working-directory: ./helm/three-tier-app
      run: |
        helm dependency update
        helm upgrade --install three-tier-app . \
          --namespace default \
          --create-namespace \
          --set frontend.service.type=LoadBalancer \
          --wait