##      V1.0.1        Imran Ali         Updated Workflow with auth + fixes     22/05/2025

name: Deploy GKE Infrastructure

on:
  repository_dispatch:
    types: [deploy-infra]

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ env.GKE_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: 'gke-gcloud-auth-plugin'

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -var="project_id=${{ env.PROJECT_ID }}" -var="cluster_name=my-new-env"

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve -var="project_id=${{ env.PROJECT_ID }}" -var="cluster_name=my-new-env"

      - name: Save Kubeconfig
        working-directory: ./terraform
        run: |
          gcloud container clusters get-credentials my-new-env --region $(terraform output -raw region)
          mkdir -p $HOME/.kube
          cp $HOME/.kube/config $HOME/.kube/gke-config
          echo "KUBE_CONFIG=$(cat $HOME/.kube/gke-config | base64 | tr -d '\n')" >> $GITHUB_ENV

      - name: Store Kubeconfig
        uses: actions/upload-artifact@v4
        with:
          name: kubeconfig
          path: $HOME/.kube/gke-config
