##############  Initial Worfklow  ####################################
#               Imran Ali          
##############  V.1.0.0   22/5/2025 ##################################

name: Setup Prerequisites

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  setup-tools:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.GKE_SA_KEY }}
          export_default_credentials: true

      - name: Setup kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl
          sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
          echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernet

      # - name: Trigger deploy-infra workflow
      #   uses: peter-evans/repository-dispatch@v3
      #   with:
      #     token: ${{ secrets.REPO_DISPATCH_PAT }}
      #     event-type: deploy-infra
